[tool.aerich]
tortoise_orm = "app.chapter6.tortoise_relationship.app.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.black]
line-length = 80
skip-magic-trailing-comma = true
target-version = ["py310"]
